### ISSUE TITLE
thank you :)

### ISSUE THREAD

**Issue by alonewolfx2** [Perfer/esp8266_ili9341#1]
firstly i want to say thank you and i am wondering one thing. this library working with ili9341but is it working on ili9340c ?

**Comment by s-sachkov** [comment]
Thank you! 
I have not ili9340c and can't testing my project with chip. In datasheet http://dn.odroid.com/ODROID-SHOW/ILI9340.pdf, I will not see big differences between ili9340c and ili9341.

**Comment by alonewolfx2** [comment]
Can you share pin wiring on esp and ili9341 side?  Something like esp8266 gpio 12->ili9341 clk?
